# other commands:
# echo "${{ steps.create-cluster.outputs.cluster-kubeconfig }}" > kubeconfig.yaml
# kubectl --kubeconfig kubeconfig.yaml get pods -A
name: test-cluster
on:
  workflow_dispatch: {}
jobs:
  cluster:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Outputs: `cluster-kubeconfig`, `cluster-id`
      - name: Create Cluster
        id: create-cluster
        uses: replicatedhq/compatibility-actions/create-cluster@v1
        with:
          api-token: ${{ secrets.REPLICATED_API_TOKEN }}
          kubernetes-distribution: openshift # eks
          kubernetes-version: 4.13.0-okd # for eks "1.25"
          cluster-name: foo
          timeout-minutes: 5
          ttl: 10m
          export-kubeconfig: true
          # kubeconfig-path: /tmp/kubeconfig # optional, specifies path for Kubeconfig file

      - name: Test
        run: |
          echo "Running a test"
          kubectl get po -A

      - name: Remove Cluster
        id: remove-cluster
        uses: replicatedhq/compatibility-actions/remove-cluster@v1
        continue-on-error: true
        with:
          api-token: ${{ secrets.REPLICATED_API_TOKEN }}
          cluster-id: ${{ steps.create-cluster.outputs.cluster-id }}