name: Demo releaser
on:
  workflow_dispatch: {}
  workflow_call:
    inputs:
      tag:
        description: The newly-discovered tag which invokes a new release.
        required: true
        type: string
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Do something
      run: echo "Doing something with tag ${{inputs.tag}}."