name: discover-versions
on:
  workflow_dispatch: {}
env:
  IMAGE_REPO: gcr.io/kubecost1/cost-model
jobs:
  discover:
    runs-on: ubuntu-latest
    steps:
      - name: Install oras
        uses: oras-project/setup-oras@v1
      - name: Discover versions
        run: |
          oras repo tags $IMAGE_REPO | egrep '^prod-1.[0-9]+.[0-9]+$' tags.txt | sort -t "." -k1,1n -k2,2n -k3,3n | tail -n1