name: test native tools
on:
  workflow_dispatch: {}
jobs:
  clis:
    runs-on: ubuntu-latest
    steps:
    - name: gh
      run: gh version
    - name: helm
      run: helm version
    - name: aws
      run: aws --version
    - name: gcloud
      run: gcloud version
    - name: python3
      run: python3 --version
    - name: go
      run: go version
    - name: Checkout
      uses: actions/checkout@v4
      with:
      #   repository: 'kubecost/release-scripts'
        path: ./zulu
    - name: See checkout
      run: ls -l .
