name: test native tools
on:
  workflow_dispatch: {}
jobs:
  clis:
    runs-on: ubuntu-latest
    steps:
    - name: Install crane
      run: |
        VERSION=$(curl -s "https://api.github.com/repos/google/go-containerregistry/releases/latest" | jq -r '.tag_name')
        OS=Linux
        ARCH=x86_64
        curl -sL "https://github.com/google/go-containerregistry/releases/download/${VERSION}/go-containerregistry_${OS}_${ARCH}.tar.gz" > go-containerregistry.tar.gz
        tar -zxvf go-containerregistry.tar.gz -C /usr/local/bin/ crane
        crane version
    - name: Show digest for gcr.io/kubecost1/cost-model-nightly:latest
      run: crane digest gcr.io/kubecost1/cost-model-nightly:latest
    - name: gh
      run: gh version
    - name: helm
      run: helm version
    - name: aws
      run: aws --version
    - name: gcloud
      run: gcloud version
    - name: python3
      run: python3 --version
    - name: go
      run: go version
    - name: Install just
      uses: extractions/setup-just@v1
    - name: just
      run: just --version
    - name: Install manifest-tool
      run: |
        mkdir -p manifest-tool
        pushd manifest-tool
        wget -q https://github.com/estesp/manifest-tool/releases/download/v2.0.8/binaries-manifest-tool-2.0.8.tar.gz
        tar -xzf binaries-manifest-tool-2.0.8.tar.gz
        cp manifest-tool-linux-amd64 manifest-tool
        echo "$(pwd)" >> $GITHUB_PATH

    - name: Check all tool versions
      run: |
        echo '#### gh version ####'
        gh version
        echo '#### go version ####'
        go version
        echo '#### helm version ####'
        helm version
        echo '#### gcloud version ####'
        gcloud version
        echo '#### aws version ####'
        aws --version
        echo '#### python3 version ####'
        python3 --version
        echo '#### just version ####'
        just --version
        echo '#### npm version ####'
        npm version
        echo '#### manifest-tool version ####'
        manifest-tool --version
