name: test native tools
on:
  workflow_dispatch: {}
jobs:
  clis:
    runs-on: ubuntu-latest
    steps:
    - name: gh
      run: gh version
    - name: helm
      run: helm version
    - name: aws
      run: aws --version
    - name: gcloud
      run: gcloud version
    - name: python
      run: python3 --version
